sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
  - master
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run ci
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./dist-demo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master