sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
  - master
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
jobs:
  include:
    - stage: build
    - script: echo "Building Library ..."
    - script: npm run build:lib
    - stage: linting
    - script: echo "Linting ..."
    - script: npm run lint
    - stage: unit-test
    - script: echo "Starting Karma unit tests..."
    - script: npm run test:once
    - stage: unit-test
    - script: echo "Starting e2e ..."
    - script: npm run e2e:demo
    - stage : publish
    - script: echo "Publishing to Github..."
    - script: npm run publish
cache:
  directories:
    - node_modules
